#pragma once
#include"Theme1_Cloud.h"
#include"Theme1_Cube.h"
#include"Theme1_House.h"
#include"Theme1_Sun.h"
#include"Theme1_Tree.h"
#include"Theme1_Wall.h"
#include"MapDeco.h"

#include"Theme2_BatStatue.h"
#include"Theme2_PigStatue_0.h"
#include"Theme2_PigStatue_1.h"
#include"Theme2_Bush_0.h"
#include"Theme2_Bush_1.h"
#include"Theme2_Bush_2.h"
#include"Theme2_Bush_3.h"
#include"Theme2_Bush_4.h"
#include"Theme2_LongTree.h"
#include"Theme2_BigLeaf.h"

#include"Theme3_AlphaPlate.h"
#include"Theme3_BrokenPlate.h"
#include"Theme3_Cloud.h"
#include"Theme3_Moss.h"
#include"Theme3_Pattern_0.h"
#include"Theme3_Pattern_1.h"
#include"Theme3_Plate.h"
#include"Theme3_SemicolonPlate.h"

#include"Theme4_Chimney.h"
#include"Theme4_Gear8.h"
#include"Theme4_Gear16.h"
#include"Theme4_Smoke_0.h"
#include"Theme4_Smoke_1.h"